#!/bin/bash

## Amy Olex
## 12/16/15

## Script that iterates through all the files in the PREPROCESSING/gatk_processing folder with the extension .recaldata.table for the next step in GATK pipeline.
## This saves the results in the PREPROCESSING/gatk_processing folder with the extension .recal.bam
## This script also can run multiple jobs at once. 

## USAGE: ./3_gatk_printReads <num jobs>


MAXJOBS=$1
TMPDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/scratch"
OUTDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/PREPROCESSING/gatk_processing"

## GATK required files
REF="/data/refGenomes/human/hg19/hg19.fa"
KNOWN="/data/refGenomes/gatk_bundle/b37/Mills_and_1000G_gold_standard.indels.b37.sites.vcf"
INTERVALS="/data/refGenomes/human/GRCh37-lite/GRCh37-lite.gatk.intervals"
KNOWNSITES="/data/refGenomes/gatk_bundle/b37/dbsnp_138.b37.vcf"

GATK="/opt/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar"

## Need to execute this from the PREPROCESSING/gatk_processing directory
cd $OUTDIR

function maxjobs {

	if [ $# -ne 1 ]
	then
		num=1
	else
		num=$1
	fi

	while [ `jobs -r | wc -l` -ge $num ]
	do
		sleep 5
	done
}

## Process all files with the .realign.bam extension with the BaseRecalibrator
ls *.recaldata.table | while read file
do
	maxjobs $MAXJOBS
	filebase=`basename $file .recaldata.table`
	bam=$filebase.realign.bam
	java -Xmx8g -Djava.io.tmpdir=$TMPDIR -jar $GATK -T PrintReads -R $REF -I $bam -BQSR $file -o $filebase.recal.bam -nct 2 &

done
