#!/bin/bash

## Amy Olex
## 12/16/15

## Script that iterates through all the files in the PREPROCESSING/gatk_processing folder with the extension .recal.bam and runs MuTect2
## NOTE:  MuTect2 is designed to run on Tumor/Normal pairs, but we don't have matched normals.  We are running the files individually without matched normals.
## This saves the results in the PREPROCESSING/gatk_variants folder with the extension .rawVariants.vcf
## This script also can run multiple jobs at once. 

## USAGE: ./5_gatk_mutect2 <num jobs>


MAXJOBS=$1
TMPDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/scratch"
OUTDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/PREPROCESSING/gatk_variants"

## GATK required files
## GATK bundle: https://www.broadinstitute.org/gatk/guide/article.php?id=1215
REF="/data/refGenomes/human/hg19/hg19.fa"
KNOWN="/data/refGenomes/gatk_bundle/b37/Mills_and_1000G_gold_standard.indels.b37.sites.vcf.gz"
#INTERVALS="/data/refGenomes/human/GRCh37-lite/GRCh37-lite.gatk.intervals"
INTERVALS="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/NexteraTargetedExome_hg19.intervals"
KNOWNSITES="/data/refGenomes/gatk_bundle/b37/dbsnp_138.b37.vcf.gz"
COSMIC="/data/refGenomes/gatk_bundle/b37/b37_cosmic_v54_120711.vcf.gz"
NORMALS="/data/refGenomes/gatk_bundle/b37/1000G_phase3_v4_20130502.sites.vcf.gz"

GATK="/opt/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar"

## Need to execute this from the PREPROCESSING/gatk_processing directory
cd /var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/PREPROCESSING/gatk_processing

function maxjobs {

	if [ $# -ne 1 ]
	then
		num=1
	else
		num=$1
	fi

	while [ `jobs -r | wc -l` -ge $num ]
	do
		sleep 5
	done
}

## Process all files with the .recal.bam
##java
#     -jar GenomeAnalysisTK.jar
#     -T HaplotypeCaller
#     -R reference.fasta
#     -I:tumor normal1.bam \
#     [--dbsnp dbSNP.vcf] \
#     [--cosmic COSMIC.vcf] \
#     --artifact_detection_mode \
#     [-L targets.interval_list] \
#     -o output.normal1.vcf

ls *.recal.bam | while read file
do
	maxjobs $MAXJOBS
	filebase=`basename $file .recal.bam`

	java -Xmx12g -Djava.io.tmpdir=$TMPDIR -jar $GATK -T MuTect2 -R $REF -I:tumor $file --genotyping_mode DISCOVERY --dbsnp $KNOWNSITES --cosmic $COSMIC --normal_panel $NORMALS --intervals $INTERVALS --artifact_detection_mode -o $OUTDIR/$filebase.rawVariants.vcf &

## NOTES: I have the --artifact_detection_mode set, but I'm not sure this should be used.  The MuTect2 documentation says this option "maintains the specified tumor LOD threshold, but disables the remaining pragmatic filters".
##	  Since we are looking at tumor files and not normals I'm think this option should not be used.



##	java -Xmx8g -Djava.io.tmpdir=$TMPDIR -jar $GATK -T HaplotypeCaller -R $REF -I $file -o $OUTDIR/$filebase.rawVariants.vcf -ERC NONE -baqGOP 30 -variant_index_type LINEAR -variant_index_parameter 128000 --genotyping_mode DISCOVERY -stand_emit_conf 10 -stand_call_conf 30 -nct 4
## NOTES:  Mikhail wanted me to run the MuTect2 somatic caller, but it requires a tumor normal pair, which we don't have here.  Thus, I don't think I can run that on this data.  
## NOTES:  The HaplotypeCaller documentation states that it is not ideal, nor should be used for, calling mutations in cancer data because it makes certain assumptions about allele frequencies that do not hold in cancer.
## NOTES:  Thus, I'm not sure what to do here or what is the best option.  I found the blog here (https://www.biostars.org/p/65080/) to be helpful on the filtering end, but I don't know what tool they used to call in the first place.

done
