#!/bin/bash

## Amy Olex
## 2/17/16

## According to this blog post (http://gatkforums.broadinstitute.org/gatk/discussion/6690/mutect2-tumor-only-mode-empty-vcfs) providing interval list does not alter the statistical caluclations, so I'm going ot leave the interval list out.
## USAGE: ./5_gatk_mutect2 <bam file>


BAM=$1
TMPDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/scratch"
OUTDIR="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/PREPROCESSING/gatk_variants"

## GATK required files
## GATK bundle: https://www.broadinstitute.org/gatk/guide/article.php?id=1215
REF="/data/refGenomes/human/hg19/hg19.fa"
KNOWN="/data/refGenomes/gatk_bundle/b37/Mills_and_1000G_gold_standard.indels.b37.sites.vcf.gz"
#INTERVALS="/var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/NexteraTargetedExome_hg19.intervals"
KNOWNSITES="/data/refGenomes/gatk_bundle/b37/dbsnp_138.b37.vcf.gz"
COSMIC="/data/refGenomes/gatk_bundle/b37/b37_cosmic_v54_120711.vcf.gz"
NORMALS="/data/refGenomes/gatk_bundle/b37/1000G_phase3_v4_20130502.sites.vcf.gz"

GATK="/opt/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar"

## Need to execute this from the PREPROCESSING/gatk_processing directory
cd /var/bioinformatics-tcga-projects/alolex/clients/MDozmorov/BRCA_WXS_VCU_Wenhu/PREPROCESSING/gatk_processing

filebase=`basename $BAM .recal.bam`

java -Xmx12g -Djava.io.tmpdir=$TMPDIR -jar $GATK -T MuTect2 -R $REF -I:tumor $BAM --genotyping_mode DISCOVERY --dbsnp $KNOWNSITES --cosmic $COSMIC --normal_panel $NORMALS -o $OUTDIR/$filebase.rawVariants.vcf


