#!/bin/bash

## 12/9/15
## Amy Olex
## Written to merge BAM files

## Input is a tab delimited file with FILE1 <tab> FILE2

my_file=$1

cat $my_file | while read file1 file2
do
	outbase=`basename $file1 .bam`
	java -Xmx8g -XX:ParallelGCThreads=2 -Djava.io.tmpdir=/home/alolex/tmp/scratch -jar /opt/picard-tools-1.115/MergeSamFiles.jar INPUT=$file1 INPUT=$file2 OUTPUT=$outbase.MERGED.bam COMMENT="Merging VCU22 run1 files that did not demultiplex properly with the corresponding run2 files."

done

echo "DONE"
