#!/bin/bash

## 10/5/16
## Amy Olex
## Written to generate and summarize the results from samtools flagstat program.
## Input is a list of files to run flagstat on.
## Output are the individual flagstat results and a summary file of all results.
##
## USAGE: ./run_flagstat_generic inputfile.txt outputfile.txt numjobs 

## Define maxjobs function
function maxjobs {
        if [ $# -ne 1 ]
        then
                num=1
        else
                num=$1
        fi

        while [ `jobs -r | wc -l` -ge $num ]
        do
                sleep 2
        done
}


# FILE needs to be a text file with file names one per line.
# OUT is the file name for the summary.
# This script is written to be run in the same directory as the BAM files.
#
# >> ./run_flagstat myfiles.txt flagstat-summary-results.txt 3


FILE=$1
OUT=$2
MAX_JOBS=$3

touch $OUT

PIDS=()

## Parse the in file and run several jobs at once.
cat $FILE | while read infile
do
	tmp=`basename $infile .bam`
	tmp_out=$tmp".flagstat.txt"
	
	if [ -e $tmp_out ]
	then
		echo "File Exists, skipping..." $tmp_out
	else	
		echo "Starting File..." $infile "...Out file is..." $tmp_out
		maxjobs $MAX_JOBS
		echo $pid > $tmp_out
		samtools flagstat $infile >> $tmp_out &
		PIDS=(${PIDS[@]} $!)
		#sums=$(tail -n+3 $screen_file | head -n7 | awk -F'\t' '{print $5 + $7 + $9 + $11}'| tr '\n' ',' | sed 's/,/\t/g' | sed 's/\t$//')
		#echo -e $pid"\t"$dir"\\"$bam"\t"$sums >> $OUT
	fi
done

wait ${PIDS[@]}

## Once all flagstat jobs have run, parse the file to get the total number, num paired, num both mapped and num properly mapped.
echo "Done files, summarizing."
echo -e "Barcode\tTotal\tDuplicates\tMapped\tPaired in Sequencing\tRead1\tRead2\tProperly Paired\tItself and Mate Mapped\tSingletons\tMate Mapped to Dif Chr\tMate Mapped to Diff Chr (mapQ>=5)" > $OUT

`ls *.flagstat.txt > flagstat-files-to-summarize.txt`

cat "flagstat-files-to-summarize.txt" | while read file
do
	values=$(cat $file | awk -F' ' '{print $1}' | tr '\n' '\t')
	echo -e $values >> $OUT
done 
